#!/usr/bin/env -S npx tsx
/**
 * Generate index.md for a Diataxis-organized documentation tree.
 *
 * Usage:
 *   npx tsx .claude/skills/diataxis/scripts/generate-index.ts [docs_root]
 *
 * Default docs_root is `docs`. Pass a different path for per-package docs:
 *
 * Behavior:
 * - Scans <docs_root> for the four Diataxis subfolders: tutorials, how-to, reference, explanation.
 * - Recursively renders nested sub-category folders (e.g. reference/cdk/, how-to/security/).
 * - Extracts H1 titles from each .md file (falls back to a Title-Cased filename).
 * - Writes <docs_root>/index.md.
 * - Skips hidden files, README.md (kept as a separate intro), and the index file itself.
 * - Honors .gitkeep markers so empty intentional folders still render with "_No documents yet._".
 * - Leaves untouched: openspec/, .github/, audit-reports/, contracts/ (those are not Diataxis).
 *
 * Adapted from arisng/github-copilot-fc (skills/diataxis/scripts/generate_index.py),
 * rewritten in TypeScript.
 *
 * No dependencies beyond Node ≥ 22 stdlib + tsx.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, posix, relative, sep } from 'node:path'
import { argv, exit, stderr, stdout } from 'node:process'

const CATEGORIES: ReadonlyArray<readonly [folder: string, label: string]> = [
	['tutorials', 'Tutorials'],
	['how-to', 'How-to Guides'],
	['reference', 'Reference'],
	['explanation', 'Explanation'],
]

const SKIP_FILES = new Set(['index.md', 'README.md'])

const isDir = (path: string): boolean => {
	try {
		return statSync(path).isDirectory()
	} catch {
		return false
	}
}

const titleCase = (slug: string): string =>
	slug.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())

const getTitle = (filepath: string): string => {
	try {
		const content = readFileSync(filepath, 'utf-8')
		for (const raw of content.split(/\r?\n/)) {
			const line = raw.trim()
			if (line.startsWith('# ')) return line.slice(2).trim()
			if (line.length > 0) break
		}
	} catch (err) {
		stderr.write(`warning: could not read ${filepath}: ${(err as Error).message}\n`)
	}
	const base = filepath.split(sep).pop() ?? filepath
	return titleCase(base.replace(/\.md$/, ''))
}

interface Entry {
	name: string
	fullPath: string
	isDirectory: boolean
	isFile: boolean
}

const listEntries = (dir: string): Entry[] =>
	readdirSync(dir).map((name) => {
		const fullPath = join(dir, name)
		const stat = statSync(fullPath)
		return { name, fullPath, isDirectory: stat.isDirectory(), isFile: stat.isFile() }
	})

const hasVisibleContent = (dir: string): boolean =>
	listEntries(dir).some((e) => e.name === '.gitkeep' || !e.name.startsWith('.'))

const toPosix = (p: string): string => p.split(sep).join(posix.sep)

const renderDirectory = (dir: string, docsRoot: string, headingLevel: number): string => {
	const entries = listEntries(dir)
	const directFiles = entries
		.filter((e) => e.isFile && e.name.endsWith('.md') && !SKIP_FILES.has(e.name))
		.sort((a, b) => a.name.localeCompare(b.name))
	const childDirs = entries
		.filter((e) => e.isDirectory && !e.name.startsWith('.'))
		.sort((a, b) => a.name.localeCompare(b.name))
	const visibleChildren = childDirs.filter((d) => hasVisibleContent(d.fullPath))
	const hasKeepMarker = entries.some((e) => e.name === '.gitkeep')

	if (directFiles.length === 0 && visibleChildren.length === 0 && !hasKeepMarker) return ''

	const heading = titleCase(dir.split(sep).pop() ?? '')
	let content = `${'#'.repeat(headingLevel)} ${heading}\n\n`

	for (const file of directFiles) {
		const title = getTitle(file.fullPath)
		const link = `${toPosix(relative(docsRoot, dir))}/${file.name}`
		content += `- [${title}](${link})\n`
	}

	if (directFiles.length > 0 && visibleChildren.length > 0) content += '\n'
	if (directFiles.length === 0 && visibleChildren.length === 0) {
		content += '- _No documents yet._\n\n'
	}

	for (const child of visibleChildren) {
		const childContent = renderDirectory(child.fullPath, docsRoot, headingLevel + 1)
		if (childContent) content += childContent
	}

	return content
}

const main = (docsRoot: string): number => {
	if (!isDir(docsRoot)) {
		stderr.write(`error: ${docsRoot} is not a directory\n`)
		return 2
	}

	const header =
		`# ${toPosix(docsRoot)} — Documentation Index\n\n` +
		'Diataxis-organized documentation. Generated by\n' +
		'`.claude/skills/diataxis/scripts/generate-index.ts`. Do not edit by hand —\n' +
		're-run the script after adding or moving files.\n\n'

	let body = ''

	for (const [folder, section] of CATEGORIES) {
		const catPath = join(docsRoot, folder)
		if (!isDir(catPath)) continue

		const entries = listEntries(catPath)
		const rootFiles = entries
			.filter((e) => e.isFile && e.name.endsWith('.md') && !SKIP_FILES.has(e.name))
			.sort((a, b) => a.name.localeCompare(b.name))
		const subdirs = entries
			.filter((e) => e.isDirectory && !e.name.startsWith('.'))
			.sort((a, b) => a.name.localeCompare(b.name))
		const visibleSubdirs = subdirs.filter((d) => hasVisibleContent(d.fullPath))

		if (rootFiles.length === 0 && visibleSubdirs.length === 0) continue

		if (body.length > 0 && !body.endsWith('\n\n')) body += '\n'
		body += `## ${section}\n\n`

		for (const file of rootFiles) {
			const title = getTitle(file.fullPath)
			body += `- [${title}](${folder}/${file.name})\n`
		}

		if (rootFiles.length > 0 && visibleSubdirs.length > 0) body += '\n'

		for (const sub of visibleSubdirs) {
			body += renderDirectory(sub.fullPath, docsRoot, 3)
			if (!body.endsWith('\n\n')) body += '\n'
		}

		if (rootFiles.length === 0) body += '\n'
	}

	if (body.length === 0) body = '_No Diataxis-categorized documents found yet._\n'

	const indexPath = join(docsRoot, 'index.md')
	writeFileSync(indexPath, (header + body).trimEnd() + '\n', 'utf-8')
	stdout.write(`wrote ${indexPath}\n`)
	return 0
}

const docsRootArg = argv[2] ?? 'docs'
exit(main(docsRootArg))
